networks:
  defense-net:
    driver: bridge

volumes:
  loki-data:
  grafana-data:
  wordpress-db-data:
  wordpress-data:
  wiki-db-data:
  wikijs-data:
  wikijs-cache:

include:
  - compose.traefik.yml
  - compose.shop.yml
  - compose.blog.yml