displayName: Defense Middleware
type: middleware
import: github.com/hebetude/defense_middleware
summary: Maybe the multilayered one will work.

testData:
  semanticInjection:
    enabled: false
    prompt: "TEST, TODO. Replace with a proper prompt later."
  textPerturbation:
    enabled: false
    targetTags: ["p"]
  